BOSS = "BOSS"
WS = "WAREHOUSE SUPERVISOR"
SALES = "SALESMAN"
WORKER = "WORKER"


PERSONEL_TYPE = (
    (BOSS, "BOSS"),
    (WS, "WAREHOUSE SUPERVISOR"),
    (SALES, "SALESMAN"),
    (WORKER, "WORKER"),
)
